name: 'Submodules Sync'

on:
  # Allows you to run this workflow manually from the Actions tab or through HTTP API
  workflow_dispatch:

  repository_dispatch:
    types: [submodule-update]

jobs:
  sync:
    name: 'Submodules Sync'
    runs-on: ubuntu-latest

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.CLONE_SUBMODULE }}
        submodules: true

    # Update references
    - name: Git Sumbodule Update
      run: |
        git pull --recurse-submodules
        git submodule update --remote --recursive

    # - name: Commit update
    #   run: |
    #     git config --global user.name 'Git bot'
    #     git config --global user.email 'bot@noreply.github.com'
    #     git remote set-url origin https://x-access-token:${{ secrets.CLONE_SUBMODULE }}@github.com/${{ github.repository }}
    #     git commit -am "Auto updated submodule references" || echo "No changes to commit"

    - name: Create Pull Request
      id: cpr
      uses: peter-evans/create-pull-request@v4
      with:
        token: ${{ secrets.CLONE_SUBMODULE }}
        commit-message: Update submodule
        committer: GitHub <noreply@github.com>
        author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
        signoff: false
        branch: submodule-update
        delete-branch: true
        title: 'Update submodule'
        body: |
          Update submodule
          - Updated with *today's* date
          - Auto-generated by [create-pull-request][1]

          [1]: https://github.com/peter-evans/create-pull-request
        assignees: haihodac-pepperstone
        reviewers: haihodac-pepperstone
        team-reviewers: |
          owners
          maintainers
        milestone: 1
        draft: false