name: check-submodule

on: [pull_request]

jobs:
  check-submodules:
    name: Check Submodule
    runs-on: ubuntu-latest
    steps:
    - name: Checkout this repo
      uses: actions/checkout@v3
    ## Step only reqired for private submodules
    - name: Checkout submodule repo
      uses: actions/checkout@v3
      with:
        repository: haihodac-pepperstone/glowing-parakeet
        path: "glowing-parakeet"
        token: ${{ secrets.PAT_FOR_PRIVATE_SUBMODULE }}
    - name: Check Submodule Name
      uses: jtmullen/submodule-branch-check-action@v1
      with:
        path: "glowing-parakeet"
        branch: "main"
        pass_if_unchanged: true
        require_head: true